# Generated by Django 3.1.5 on 2023-10-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
