# Generated by Django 3.1.5 on 2023-10-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231008_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='text',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
