# Generated by Django 3.1.5 on 2023-10-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231008_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='need1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need10',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need4',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need5',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need6',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need7',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need8',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='need9',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='research',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.category'),
        ),
        migrations.AddField(
            model_name='research',
            name='teg1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teg1', to='app.category'),
        ),
        migrations.AddField(
            model_name='research',
            name='teg2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teg2', to='app.category'),
        ),
        migrations.AddField(
            model_name='research',
            name='teg3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teg3', to='app.category'),
        ),
        migrations.AddField(
            model_name='research',
            name='teg4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teg4', to='app.category'),
        ),
        migrations.AddField(
            model_name='research',
            name='teg5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teg5', to='app.category'),
        ),
    ]
