# Generated by Django 3.1.5 on 2023-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cv',
            new_name='file',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
