# Generated by Django 3.1.5 on 2023-10-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='post',
            new_name='research',
        ),
    ]
